### ISSUE TITLE
Which Script to use for Step: UMI clustering ?

### ISSUE THREAD

**Issue by jkbenotmane** [KCCG/rageseq#3]
How was the described step UMI clustering done for the Nanopore Reads and which of the Script in the Repo does it ?

All the best

**Comment by Psy-Fer** [comment]
Hey, sorry for not getting back to you right away. In the RAGE-seq manuscript, we didn't do UMI clustering for the nanopore data, as we were relying on assembly as a proxy. We know this wasn't ideal but it worked for the specific context in which we used it.

The current scripts do not include UMI clustering for this reason, though we have since expanded the method for future works in progress.

**Comment by yuchen345** [comment]
Hi @Psy-Fer  do you mean you extracted the UMI sequences after cell barcodes but did not use the UMI message during reads assembling?  By the way, could you please give more explanation of --barcodeNumber, i got error with input as follows
![图片](https://user-images.githubusercontent.com/71202087/218699604-0a266898-243a-4a16-b2b0-d676aa09ecff.png)
Best wishes!

**Comment by Psy-Fer** [comment]
Hello,

Yes we didn't use the UMIs as we were assembling TCR/BCR sequences through an alignment and assembly method.
This is not idea, but at the time, it was a working solution. 

for the barcode list, it has a particular structure. See the examples here https://github.com/KCCG/rageseq/tree/master/cell_barcodes 

the -n argument is for the barcode to be processes. As we used array jobs on a HPC to do each barcode individually in parallel. The same can be achieved using a for loop over the number of lines in the barcode file.
